### ISSUE TITLE
Make references more user friendly in Rust

### ISSUE THREAD

**Issue by VeaaC** [heremaps/flatdata#135]
Rust has the problem that all of flatdata's references are strongly types: They use fixed-size integer types, not std::size/std::usize.

This means Rust code is often littered with:
```
g.strings().substring(vertices.at(data.to_ref() as usize).name_ref() as usize)?;
g.edges().slice(vertex.edges().start as usize .. vertex.edges().end as usize);
```

I propose adding the following:
* ```at``` method for u8, u16, u32, u64
* ```slice``` method for ```Range<u8, u16, u32, u64>```
*  ```substring``` method for u8, u16, u32, u64

This means flatdata will not support architecture that have smaller address space.... but since flatdata use memory mapped files it cannot do so anyway.

Thoughts @boxdot ?

**Comment by boxdot** [comment]
> Rust has the problem that all of flatdata's references are strongly types

I think this is also a huge benefit. :)

About implementation. Since there is no overloading, I guess you want to templatize? I implemented this feature by using `num-trait::ToPrimitive`, however now I am not sure it is a good idea. Rust uses usize everywhere, and even at, slice, substring are more ergonomic, all other methods in Rust like skip, take, nth, etc... are still enforcing to use usize. I guess this is just the idiomatic way to go.

Another way would be to introduce unsized type in flatdata like usize.

**Comment by VeaaC** [comment]
File formats need fixed sizes, I would not add usize/isize to the flatdata grammar.

**Comment by VeaaC** [comment]
Closing since we moved to native slices
