### ISSUE TITLE
Comparison to FlatBuffers

### ISSUE THREAD

**Issue by hallahan** [heremaps/flatdata#231]
Flatdata seems to be inspired by Google FlatBuffers, though it has more to it, for example, there are utilities to handle memmapping of files, etc.

Is there any documentation that compares / contrasts Flatdata to other binary formats such as Flatbuffers, Protocol Buffers, Cap'n Proto, Msgpack, etc?

**Comment by VeaaC** [comment]
It is not really inspired by message-based protocols (protobuf, flatbuffer, etc): These are optimized for (fully) encoding small/medium sized messages in a flexible way (forward and backward compatible).

Flatdata is instead optimized to store read-only medium/large data with 0-overhead, random access, and without forward/backward compatibility.

The use cases rarely overlap:

Flatbuffers/Protobuf/Cap'n Proto/etc:
* RPC calls
* Storing small data packages
* REST service APIs

Flatdata:
* Database for geo-service, e.g. Routing, Isoline, Traffic
* Data format for large data with unchanging schema, e.g. https://github.com/boxdot/osmflat-rs

**Comment by hallahan** [comment]
I have tried out osmflat-rs, and the speed at which I can convert a .osm.pbf to .osmflat on a standard laptop is impressive. The work done to create indices of OSM entities, with a global string dictionary of the attributes and tags, is very cool. It proves the point that a lot can be achieved on a single machine for large datasets, if done right.

Memmapping a large data set, from my understanding, is an intended use case of Flatbuffers. Zero copy reads is the main point behind Flatbuffers. They essentially are providing an schema language that can be compiled into code of your target language, as an alternative to hand-crafted C structs of the olden days. Isn't the same random access achieved with a large memmapped Flatbuffer with an index?

What is the essential difference between the contents of data encoded in a flatdata struct, compared with a [flatbuffer struct](https://google.github.io/flatbuffers/md__internals.html)? 

A couple of differences I'm seeing:

Flatdata:
* Does not handle float and string types, casting needs to be handled by the client.
* You can explicitly set the width of items in the struct, allowing the generated code to pack for you.
* The logistics of memmap'ing a file is [already worked out for you](https://github.com/heremaps/flatdata/blob/b1d77cb186f7c420f481c32487e12b166eed5504/flatdata-rs/lib/src/filestorage.rs#L20), and this is part of the archive in the generated code.
* Ability to reference items in other structs via a "foreign key" mechanism. (@explicit_reference)

Flatbuffer:
* Less control of packing items into a struct. The items in a struct are aligned to the size of the largest item. Packing must be manually done by the client.
* Tables can be used, providing the ability of having optional or default values.
* Floats and strings are supported.
* More languages (JavaScript) are supported.
* No mechanism for "foreign key" referencing.

Flatdata archives seem similar to Flatbuffer tables? Is the archive similarly implemented as a vtable?

Is there anything I'm saying that is incorrect? Are there capabilities with flatdata that I'm missing?

**Comment by VeaaC** [comment]
The big differences between Flatdata and Flatbuffers in my opinion are:

Flatbuffers:
* Not 0-overhead most of the time: It uses extra space and runtime to achieve forward and backward compatibility of the schema (the vtables). It has less overhead than Protobuf, though.
* Does not manage "archives"/"databases": Creating (e.g. streaming data efficiently to the disk, instead of having to construct everything in RAM before serializing), opening (memory mapping), etc
* No support for packed data (defining exact bit width)

These things were the main motivation for us to develop Flatdata: No existing DSL supported all of them.

Especially not being able to incrementally construct a Flatbuffer message is a deal breaker for using it for anything but smaller/medium sized messages. That's why I referred to those protocols as `message-based protocols`: If you use them to encode large amounts of data, you usually encode smaller messages in a larger "container" (e.g. check OpenstreetMap's PBF format: It encodes a list of Protobuffer messages by manually encoding them into a stream of bytes).

Flatdata actually supports strings, but it involves more manual work: You normally create a `raw_data` string block, put 0-terminated string in it, and reference them from structures (check out the `coappearances` example, it does something like that, osm-flat as well). It does not, though, support floating point values: Those are very tricky to make work cross-platform without performance overhead, and almost all usecases we encountered so far were actually better served by fixed-point numbers stored as integers. We are open to contributions, though, in case somebody is interested to work on that feature.

One thing that Flatbuffers does better than Flatdata is being able to store structures with large amount of optional values compactly: Flatdata supports optional values (via sentinel states), but they always take up space (often this can be mitigated, though, by adding an extra indirection).

**Comment by hallahan** [comment]
Thank you for the helpful comparison. 

From my understanding, both FlatBuffers and ProtocolBuffers recommend against having large message sizes, and instead, they either have an integer before the message that defines how many bytes the next message is, or an index points to message offsets and lengths. Then, you can just have a large buffer of many messages. That solves the problem, but I agree it would be nice if it was directly built into the schema definitions. I like how this is built into Flatdata's archives.

👍
