### ISSUE TITLE
Optional struct member via sentinel values

### ISSUE THREAD

**Issue by VeaaC** [heremaps/flatdata#80]
Often we have optional struct fields implemented through special constants, e.g:

```
const u32 INVALID_XYZ = 0xffff;

struct A {
    // INVALID_XYZ in case it's empty
    x : u32;
}
```

How about supporting that in the generated code properly: exposing an ```Option< T >``` instead of ```T```?

Schema suggestion:

```
const u32 INVALID_XYZ = 0xffff;

struct A {
   @null_value( INVALID_XYZ )
    x : u32;
}
```

What do you think @boxdot @imagovrn ?

**Comment by boxdot** [comment]
I like the idea. 

What would be the extended interface of `A` to work with null values? I guess, when creating `A`, `x` will be `INVALID_XYZ` instead of 0 by default. What about checks for `is_null`? Not sure, how to express this.

If we think about Rust implementation, then this `x` is an optional field. Not sure, it is important what is the actual value of `INVALID_XYZ`. In that case, the getter `A::x()` would just return `Option<u32>`. What about C++/Python?

**Comment by VeaaC** [comment]
Good point about the default value: We only support 0s at the moment. So ```null``` would not be the default in many cases.

C++ does not have ```optional``` yet (at least until 17), so we either role our own or wait for 17. Python has ```Optional```.

**Comment by boxdot** [comment]
> C++ does not have `optional` yet (at least until 17), so we either role our own or wait for 17. Python has `Optional`.

We could provide some functions on the interface of `A` to check if x is null, something like `x_is_null`. However, this could lead to very long and non-discoverable names.

**Comment by VeaaC** [comment]
Done
